version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://radiator_user:radiator_pass@db:5432/radiator_db
      - DATABASE_URL_SYNC=postgresql://radiator_user:radiator_pass@db:5432/radiator_db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn radiator.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=radiator_db
      - POSTGRES_USER=radiator_user
      - POSTGRES_PASSWORD=radiator_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radiator_user -d radiator_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
