"""Add key field to tracker_tasks table

Revision ID: 5d4313ca2c02
Revises: add_tracker_tables
Create Date: 2025-08-27 23:14:26.399018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4313ca2c02'
down_revision = 'add_tracker_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tracker_task_history_task_id'), 'tracker_task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_tracker_task_history_tracker_id'), 'tracker_task_history', ['tracker_id'], unique=False)
    op.add_column('tracker_tasks', sa.Column('key', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_tracker_tasks_tracker_id'), table_name='tracker_tasks')
    op.create_index('idx_tracker_tasks_tracker_id', 'tracker_tasks', ['tracker_id'], unique=False)
    op.create_index('idx_tracker_tasks_key', 'tracker_tasks', ['key'], unique=False)
    op.create_index(op.f('ix_tracker_tasks_id'), 'tracker_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tracker_tasks_key'), 'tracker_tasks', ['key'], unique=False)
    op.create_index(op.f('ix_tracker_tasks_tracker_id'), 'tracker_tasks', ['tracker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_tasks_tracker_id'), table_name='tracker_tasks')
    op.drop_index(op.f('ix_tracker_tasks_key'), table_name='tracker_tasks')
    op.drop_index(op.f('ix_tracker_tasks_id'), table_name='tracker_tasks')
    op.drop_index('idx_tracker_tasks_key', table_name='tracker_tasks')
    op.drop_index('idx_tracker_tasks_tracker_id', table_name='tracker_tasks')
    op.create_index(op.f('idx_tracker_tasks_tracker_id'), 'tracker_tasks', ['tracker_id'], unique=True)
    op.drop_column('tracker_tasks', 'key')
    op.drop_index(op.f('ix_tracker_task_history_tracker_id'), table_name='tracker_task_history')
    op.drop_index(op.f('ix_tracker_task_history_task_id'), table_name='tracker_task_history')
    # ### end Alembic commands ###
